[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://turnupspot-api.onrender.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Custom domain configuration for turnupspot.com
[[redirects]]
  from = "https://turnupspot.com/*"
  to = "https://www.turnupspot.com/:splat"
  status = 301
  force = true

# SPA Fallback for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200