services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: turnupspot_backend
    ports:
      - "8000:8000"

    depends_on:
      # - db
      - mongo
      - redis
    volumes:
      - .:/app
  # db:
  #   image: postgres:15
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 1234
  #     POSTGRES_DB: turnupspot
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  
    
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery_app.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres.vwawhztoptaxbejmtfnw:KgtKZoZ9VQik6T5K@aws-0-ca-central-1.pooler.supabase.com:5432/postgres

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile  
    command: celery -A app.celery_app.celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres.vwawhztoptaxbejmtfnw:KgtKZoZ9VQik6T5K@aws-0-ca-central-1.pooler.supabase.com:5432/postgres
      
volumes:
  postgres_data:
  mongo_data:
  redis_data:
