services:
  backend:
    build: .
    container_name: turnupspot_backend
    ports:
      - "8000:8000"

    depends_on:
      # - db
      - mongo
      - redis
    volumes:
      - .:/app
  # db:
  #   image: postgres:15
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 1234
  #     POSTGRES_DB: turnupspot
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
volumes:
  postgres_data:
  mongo_data:
  redis_data:
