"""add_playing_days_table

Revision ID: 8d29295c57a2
Revises: 228bd28d70f6
Create Date: 2025-07-23 07:25:00.873825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d29295c57a2'
down_revision = '228bd28d70f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playing_days',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sport_group_id', sa.String(), nullable=True),
    sa.Column('day', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='day')),
    sa.ForeignKeyConstraint(['sport_group_id'], ['sport_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.drop_column('sport_groups', 'playing_days')
    # ### end Alembic commands ###


def downgrade():
    # Add back the playing_days column to sport_groups
    op.add_column('sport_groups',
        sa.Column('playing_days', sa.String(), nullable=True, default="0,2,4")
    )
    
    # Drop the playing_days table
    op.drop_table('playing_days')