"""add match state and coin toss JSON fields

Revision ID: 98d1ae7dcbb8
Revises: 123456789abc
Create Date: 2025-07-16 23:59:02.244900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98d1ae7dcbb8'
down_revision = '123456789abc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_game_day_participants_game_id', table_name='game_day_participants')
    op.create_index(op.f('ix_game_day_participants_id'), 'game_day_participants', ['id'], unique=False)
    op.drop_constraint('game_day_participants_game_id_fkey', 'game_day_participants', type_='foreignkey')
    op.create_foreign_key(None, 'game_day_participants', 'games', ['game_id'], ['id'])
    op.add_column('games', sa.Column('completed_matches', sa.JSON(), nullable=True))
    op.add_column('games', sa.Column('current_match', sa.JSON(), nullable=True))
    op.add_column('games', sa.Column('upcoming_match', sa.JSON(), nullable=True))
    op.add_column('games', sa.Column('coin_toss_state', sa.JSON(), nullable=True))
    op.alter_column('sport_groups', 'playing_days',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sport_groups', 'game_start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('sport_groups', 'game_end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sport_groups', 'game_end_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('sport_groups', 'game_start_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('sport_groups', 'playing_days',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('games', 'coin_toss_state')
    op.drop_column('games', 'upcoming_match')
    op.drop_column('games', 'current_match')
    op.drop_column('games', 'completed_matches')
    op.drop_constraint(None, 'game_day_participants', type_='foreignkey')
    op.create_foreign_key('game_day_participants_game_id_fkey', 'game_day_participants', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_game_day_participants_id'), table_name='game_day_participants')
    op.create_index('idx_game_day_participants_game_id', 'game_day_participants', ['game_id'], unique=False)
    # ### end Alembic commands ###