"""Remove duplicate date column from games table

Revision ID: ba462233fa5e
Revises: f46abf58eb28
Create Date: 2025-09-02 19:07:02.089112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba462233fa5e'
down_revision = 'f46abf58eb28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('match_duration_seconds', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('timer_started_at', sa.DateTime(), nullable=True))
    op.add_column('games', sa.Column('timer_remaining_seconds', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('timer_is_running', sa.Boolean(), nullable=True))
    op.add_column('games', sa.Column('current_match_team_a', sa.String(), nullable=True))
    op.add_column('games', sa.Column('current_match_team_b', sa.String(), nullable=True))
    op.add_column('games', sa.Column('current_match_team_a_score', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('current_match_team_b_score', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('current_match_started_at', sa.DateTime(), nullable=True))
    op.add_column('games', sa.Column('team_rotation_order', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('current_rotation_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'current_rotation_index')
    op.drop_column('games', 'team_rotation_order')
    op.drop_column('games', 'current_match_started_at')
    op.drop_column('games', 'current_match_team_b_score')
    op.drop_column('games', 'current_match_team_a_score')
    op.drop_column('games', 'current_match_team_b')
    op.drop_column('games', 'current_match_team_a')
    op.drop_column('games', 'timer_is_running')
    op.drop_column('games', 'timer_remaining_seconds')
    op.drop_column('games', 'timer_started_at')
    op.drop_column('games', 'match_duration_seconds')
    # ### end Alembic commands ###