"""Add game_config and min_players_per_team to SportGroup

Revision ID: edaf6e2a3eac
Revises: 47826c578353
Create Date: 2025-12-04 21:43:59.511461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edaf6e2a3eac'
down_revision = '47826c578353'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sport_groups', sa.Column('game_config', sa.Text(), nullable=True))
    op.add_column('sport_groups', sa.Column('min_players_per_team', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sport_groups', 'min_players_per_team')
    op.drop_column('sport_groups', 'game_config')
    # ### end Alembic commands ###