"""Add Match model and MatchStatus enum

Revision ID: f46abf58eb28
Revises: 7d68680da5bf
Create Date: 2025-08-27 19:37:03.648664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46abf58eb28'
down_revision = '7d68680da5bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('team_a_id', sa.String(), nullable=False),
    sa.Column('team_b_id', sa.String(), nullable=False),
    sa.Column('team_a_score', sa.Integer(), nullable=True),
    sa.Column('team_b_score', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.String(), nullable=True),
    sa.Column('is_draw', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='matchstatus'), nullable=True),
    sa.Column('referee_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['referee_id'], ['sport_group_members.id'], ),
    sa.ForeignKeyConstraint(['team_a_id'], ['game_teams.id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['game_teams.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['game_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###